// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: brands.sql

package sqlc

import (
	"context"
)

const getBrandBySlug = `-- name: GetBrandBySlug :one
SELECT id, name, slug, logo_url, is_local, created_at, updated_at
FROM brands
WHERE slug = $1
`

func (q *Queries) GetBrandBySlug(ctx context.Context, slug string) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrandBySlug, slug)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.IsLocal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBrands = `-- name: ListBrands :many
SELECT id, name, slug, logo_url, is_local, created_at, updated_at
FROM brands
ORDER BY name ASC
`

func (q *Queries) ListBrands(ctx context.Context) ([]Brand, error) {
	rows, err := q.db.Query(ctx, listBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Brand{}
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LogoUrl,
			&i.IsLocal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
