// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: misc.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestExchangeRate = `-- name: GetLatestExchangeRate :one
SELECT id, base_currency, target_currency, rate, recorded_date
FROM exchange_rates
WHERE base_currency = $1 AND target_currency = $2
ORDER BY recorded_date DESC
LIMIT 1
`

type GetLatestExchangeRateParams struct {
	BaseCurrency   string `json:"base_currency"`
	TargetCurrency string `json:"target_currency"`
}

func (q *Queries) GetLatestExchangeRate(ctx context.Context, arg GetLatestExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, getLatestExchangeRate, arg.BaseCurrency, arg.TargetCurrency)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.BaseCurrency,
		&i.TargetCurrency,
		&i.Rate,
		&i.RecordedDate,
	)
	return i, err
}

const getSizeConversion = `-- name: GetSizeConversion :many
SELECT id, reference_brand_id, target_brand_id, reference_size, target_size, category
FROM size_conversion_matrix
WHERE reference_brand_id = $1 AND target_brand_id = $2 AND reference_size = $3
`

type GetSizeConversionParams struct {
	ReferenceBrandID pgtype.UUID `json:"reference_brand_id"`
	TargetBrandID    pgtype.UUID `json:"target_brand_id"`
	ReferenceSize    string      `json:"reference_size"`
}

func (q *Queries) GetSizeConversion(ctx context.Context, arg GetSizeConversionParams) ([]SizeConversionMatrix, error) {
	rows, err := q.db.Query(ctx, getSizeConversion, arg.ReferenceBrandID, arg.TargetBrandID, arg.ReferenceSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SizeConversionMatrix{}
	for rows.Next() {
		var i SizeConversionMatrix
		if err := rows.Scan(
			&i.ID,
			&i.ReferenceBrandID,
			&i.TargetBrandID,
			&i.ReferenceSize,
			&i.TargetSize,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSizePreferences = `-- name: GetUserSizePreferences :many
SELECT id, user_id, brand_id, size
FROM user_size_preferences
WHERE user_id = $1
`

func (q *Queries) GetUserSizePreferences(ctx context.Context, userID pgtype.UUID) ([]UserSizePreference, error) {
	rows, err := q.db.Query(ctx, getUserSizePreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSizePreference{}
	for rows.Next() {
		var i UserSizePreference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BrandID,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBrandsAutocomplete = `-- name: SearchBrandsAutocomplete :many
SELECT id, name, slug
FROM brands
WHERE name ILIKE '%' || $1::text || '%'
ORDER BY name ASC
LIMIT 5
`

type SearchBrandsAutocompleteRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Slug string      `json:"slug"`
}

func (q *Queries) SearchBrandsAutocomplete(ctx context.Context, query string) ([]SearchBrandsAutocompleteRow, error) {
	rows, err := q.db.Query(ctx, searchBrandsAutocomplete, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchBrandsAutocompleteRow{}
	for rows.Next() {
		var i SearchBrandsAutocompleteRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProductsAutocomplete = `-- name: SearchProductsAutocomplete :many
SELECT id, name, slug
FROM products
WHERE name ILIKE '%' || $1::text || '%'
ORDER BY name ASC
LIMIT 10
`

type SearchProductsAutocompleteRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Slug string      `json:"slug"`
}

func (q *Queries) SearchProductsAutocomplete(ctx context.Context, query string) ([]SearchProductsAutocompleteRow, error) {
	rows, err := q.db.Query(ctx, searchProductsAutocomplete, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProductsAutocompleteRow{}
	for rows.Next() {
		var i SearchProductsAutocompleteRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExchangeRate = `-- name: UpsertExchangeRate :exec
INSERT INTO exchange_rates (base_currency, target_currency, rate, recorded_date)
VALUES ($1, $2, $3, $4)
ON CONFLICT (base_currency, target_currency, recorded_date)
DO UPDATE SET rate = EXCLUDED.rate
`

type UpsertExchangeRateParams struct {
	BaseCurrency   string         `json:"base_currency"`
	TargetCurrency string         `json:"target_currency"`
	Rate           pgtype.Numeric `json:"rate"`
	RecordedDate   pgtype.Date    `json:"recorded_date"`
}

func (q *Queries) UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error {
	_, err := q.db.Exec(ctx, upsertExchangeRate,
		arg.BaseCurrency,
		arg.TargetCurrency,
		arg.Rate,
		arg.RecordedDate,
	)
	return err
}

const upsertUserSizePreference = `-- name: UpsertUserSizePreference :one
INSERT INTO user_size_preferences (user_id, brand_id, size)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, brand_id) DO UPDATE SET size = EXCLUDED.size
RETURNING id, user_id, brand_id, size
`

type UpsertUserSizePreferenceParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	BrandID pgtype.UUID `json:"brand_id"`
	Size    string      `json:"size"`
}

func (q *Queries) UpsertUserSizePreference(ctx context.Context, arg UpsertUserSizePreferenceParams) (UserSizePreference, error) {
	row := q.db.QueryRow(ctx, upsertUserSizePreference, arg.UserID, arg.BrandID, arg.Size)
	var i UserSizePreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BrandID,
		&i.Size,
	)
	return i, err
}
