// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Action    string             `json:"action"`
	IpAddress pgtype.Text        `json:"ip_address"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Brand struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	LogoUrl   pgtype.Text        `json:"logo_url"`
	IsLocal   bool               `json:"is_local"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type EmailVerificationToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ExchangeRate struct {
	ID             pgtype.UUID    `json:"id"`
	BaseCurrency   string         `json:"base_currency"`
	TargetCurrency string         `json:"target_currency"`
	Rate           pgtype.Numeric `json:"rate"`
	RecordedDate   pgtype.Date    `json:"recorded_date"`
}

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	ActionUrl pgtype.Text        `json:"action_url"`
	IsRead    bool               `json:"is_read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PasswordResetToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PriceHistory struct {
	ID           pgtype.UUID    `json:"id"`
	ProductID    pgtype.UUID    `json:"product_id"`
	StoreID      pgtype.UUID    `json:"store_id"`
	Price        pgtype.Numeric `json:"price"`
	RecordedDate pgtype.Date    `json:"recorded_date"`
}

type Product struct {
	ID         pgtype.UUID        `json:"id"`
	BrandID    pgtype.UUID        `json:"brand_id"`
	Name       string             `json:"name"`
	Slug       string             `json:"slug"`
	Category   string             `json:"category"`
	Attributes []byte             `json:"attributes"`
	IsLimited  bool               `json:"is_limited"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ProductImage struct {
	ID        pgtype.UUID `json:"id"`
	ProductID pgtype.UUID `json:"product_id"`
	Url       string      `json:"url"`
	SortOrder int32       `json:"sort_order"`
}

type ProductOffer struct {
	ID           pgtype.UUID        `json:"id"`
	ProductID    pgtype.UUID        `json:"product_id"`
	StoreID      pgtype.UUID        `json:"store_id"`
	Price        pgtype.Numeric     `json:"price"`
	Currency     string             `json:"currency"`
	InStock      bool               `json:"in_stock"`
	Size         pgtype.Text        `json:"size"`
	AffiliateUrl string             `json:"affiliate_url"`
	ScrapedAt    pgtype.Timestamptz `json:"scraped_at"`
}

type ProductTranslation struct {
	ID          pgtype.UUID `json:"id"`
	ProductID   pgtype.UUID `json:"product_id"`
	Locale      string      `json:"locale"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type ProductView struct {
	ID        pgtype.UUID        `json:"id"`
	ProductID pgtype.UUID        `json:"product_id"`
	ViewedAt  pgtype.Timestamptz `json:"viewed_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Review struct {
	ID          pgtype.UUID        `json:"id"`
	ProductID   pgtype.UUID        `json:"product_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Rating      int32              `json:"rating"`
	Comment     pgtype.Text        `json:"comment"`
	FitFeedback pgtype.Text        `json:"fit_feedback"`
	IsFlagged   bool               `json:"is_flagged"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ReviewReport struct {
	ID         pgtype.UUID        `json:"id"`
	ReviewID   pgtype.UUID        `json:"review_id"`
	ReportedBy pgtype.UUID        `json:"reported_by"`
	Reason     pgtype.Text        `json:"reason"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type SizeConversionMatrix struct {
	ID               pgtype.UUID `json:"id"`
	ReferenceBrandID pgtype.UUID `json:"reference_brand_id"`
	TargetBrandID    pgtype.UUID `json:"target_brand_id"`
	ReferenceSize    string      `json:"reference_size"`
	TargetSize       string      `json:"target_size"`
	Category         pgtype.Text `json:"category"`
}

type Store struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Type             string             `json:"type"`
	AffiliateNetwork pgtype.Text        `json:"affiliate_network"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                pgtype.UUID        `json:"id"`
	Email             string             `json:"email"`
	PasswordHash      string             `json:"password_hash"`
	Name              string             `json:"name"`
	OnboardingFocus   pgtype.Text        `json:"onboarding_focus"`
	PreferredLanguage string             `json:"preferred_language"`
	PreferredCurrency string             `json:"preferred_currency"`
	EmailVerified     bool               `json:"email_verified"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type UserSizePreference struct {
	ID      pgtype.UUID `json:"id"`
	UserID  pgtype.UUID `json:"user_id"`
	BrandID pgtype.UUID `json:"brand_id"`
	Size    string      `json:"size"`
}

type Wishlist struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ProductID   pgtype.UUID        `json:"product_id"`
	AlertActive bool               `json:"alert_active"`
	AlertType   pgtype.Text        `json:"alert_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
