// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOfferByID = `-- name: GetOfferByID :one
SELECT id, product_id, store_id, price, currency, in_stock, size, affiliate_url, scraped_at
FROM product_offers
WHERE id = $1
`

func (q *Queries) GetOfferByID(ctx context.Context, id pgtype.UUID) (ProductOffer, error) {
	row := q.db.QueryRow(ctx, getOfferByID, id)
	var i ProductOffer
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.StoreID,
		&i.Price,
		&i.Currency,
		&i.InStock,
		&i.Size,
		&i.AffiliateUrl,
		&i.ScrapedAt,
	)
	return i, err
}
