// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipeline.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProductOffer = `-- name: CreateProductOffer :one
INSERT INTO product_offers (id, product_id, store_id, price, currency, in_stock, affiliate_url)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6)
RETURNING id, product_id, store_id, price, currency, in_stock, size, affiliate_url, scraped_at
`

type CreateProductOfferParams struct {
	ProductID    pgtype.UUID    `json:"product_id"`
	StoreID      pgtype.UUID    `json:"store_id"`
	Price        pgtype.Numeric `json:"price"`
	Currency     string         `json:"currency"`
	InStock      bool           `json:"in_stock"`
	AffiliateUrl string         `json:"affiliate_url"`
}

func (q *Queries) CreateProductOffer(ctx context.Context, arg CreateProductOfferParams) (ProductOffer, error) {
	row := q.db.QueryRow(ctx, createProductOffer,
		arg.ProductID,
		arg.StoreID,
		arg.Price,
		arg.Currency,
		arg.InStock,
		arg.AffiliateUrl,
	)
	var i ProductOffer
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.StoreID,
		&i.Price,
		&i.Currency,
		&i.InStock,
		&i.Size,
		&i.AffiliateUrl,
		&i.ScrapedAt,
	)
	return i, err
}

const createStore = `-- name: CreateStore :one
INSERT INTO stores (id, name, type, affiliate_network)
VALUES (gen_random_uuid(), $1, $2, $3)
RETURNING id, name, type, affiliate_network, created_at
`

type CreateStoreParams struct {
	Name             string      `json:"name"`
	Type             string      `json:"type"`
	AffiliateNetwork pgtype.Text `json:"affiliate_network"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStore, arg.Name, arg.Type, arg.AffiliateNetwork)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.AffiliateNetwork,
		&i.CreatedAt,
	)
	return i, err
}

const getOfferByProductAndStore = `-- name: GetOfferByProductAndStore :one
SELECT id, product_id, store_id, price, currency, in_stock, size, affiliate_url, scraped_at FROM product_offers WHERE product_id = $1 AND store_id = $2
`

type GetOfferByProductAndStoreParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	StoreID   pgtype.UUID `json:"store_id"`
}

func (q *Queries) GetOfferByProductAndStore(ctx context.Context, arg GetOfferByProductAndStoreParams) (ProductOffer, error) {
	row := q.db.QueryRow(ctx, getOfferByProductAndStore, arg.ProductID, arg.StoreID)
	var i ProductOffer
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.StoreID,
		&i.Price,
		&i.Currency,
		&i.InStock,
		&i.Size,
		&i.AffiliateUrl,
		&i.ScrapedAt,
	)
	return i, err
}

const getStoreByName = `-- name: GetStoreByName :one
SELECT id, name, type, affiliate_network, created_at FROM stores WHERE name = $1
`

func (q *Queries) GetStoreByName(ctx context.Context, name string) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByName, name)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.AffiliateNetwork,
		&i.CreatedAt,
	)
	return i, err
}

const replaceProductImage = `-- name: ReplaceProductImage :exec
WITH deleted AS (
  DELETE FROM product_images WHERE product_id = $1
)
INSERT INTO product_images (id, product_id, url, sort_order)
SELECT gen_random_uuid(), $1, $2, 0
WHERE $2 != ''
`

type ReplaceProductImageParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	Url       string      `json:"url"`
}

func (q *Queries) ReplaceProductImage(ctx context.Context, arg ReplaceProductImageParams) error {
	_, err := q.db.Exec(ctx, replaceProductImage, arg.ProductID, arg.Url)
	return err
}

const updateProductOffer = `-- name: UpdateProductOffer :exec
UPDATE product_offers
SET price = $3, currency = $4, in_stock = $5, affiliate_url = $6, scraped_at = now()
WHERE product_id = $1 AND store_id = $2
`

type UpdateProductOfferParams struct {
	ProductID    pgtype.UUID    `json:"product_id"`
	StoreID      pgtype.UUID    `json:"store_id"`
	Price        pgtype.Numeric `json:"price"`
	Currency     string         `json:"currency"`
	InStock      bool           `json:"in_stock"`
	AffiliateUrl string         `json:"affiliate_url"`
}

func (q *Queries) UpdateProductOffer(ctx context.Context, arg UpdateProductOfferParams) error {
	_, err := q.db.Exec(ctx, updateProductOffer,
		arg.ProductID,
		arg.StoreID,
		arg.Price,
		arg.Currency,
		arg.InStock,
		arg.AffiliateUrl,
	)
	return err
}

const upsertPriceHistoryToday = `-- name: UpsertPriceHistoryToday :exec
INSERT INTO price_history (id, product_id, store_id, price, recorded_date)
VALUES (gen_random_uuid(), $1, $2, $3, CURRENT_DATE)
ON CONFLICT (product_id, store_id, recorded_date) DO UPDATE SET price = EXCLUDED.price
`

type UpsertPriceHistoryTodayParams struct {
	ProductID pgtype.UUID    `json:"product_id"`
	StoreID   pgtype.UUID    `json:"store_id"`
	Price     pgtype.Numeric `json:"price"`
}

func (q *Queries) UpsertPriceHistoryToday(ctx context.Context, arg UpsertPriceHistoryTodayParams) error {
	_, err := q.db.Exec(ctx, upsertPriceHistoryToday, arg.ProductID, arg.StoreID, arg.Price)
	return err
}

const upsertProduct = `-- name: UpsertProduct :one
INSERT INTO products (id, brand_id, name, slug, category, is_limited)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  is_limited = EXCLUDED.is_limited,
  updated_at = now()
RETURNING id, brand_id, name, slug, category, attributes, is_limited, created_at, updated_at
`

type UpsertProductParams struct {
	BrandID   pgtype.UUID `json:"brand_id"`
	Name      string      `json:"name"`
	Slug      string      `json:"slug"`
	Category  string      `json:"category"`
	IsLimited bool        `json:"is_limited"`
}

func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, upsertProduct,
		arg.BrandID,
		arg.Name,
		arg.Slug,
		arg.Category,
		arg.IsLimited,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Name,
		&i.Slug,
		&i.Category,
		&i.Attributes,
		&i.IsLimited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
