// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT
  p.id, p.brand_id, p.name, p.slug, p.category, p.attributes, p.is_limited, p.created_at, p.updated_at,
  b.name AS brand_name,
  b.slug AS brand_slug,
  COALESCE((SELECT url FROM product_images pi WHERE pi.product_id = p.id ORDER BY pi.sort_order LIMIT 1), '')::text AS image_url
FROM products p
JOIN brands b ON b.id = p.brand_id
WHERE p.slug = $1
`

type GetProductBySlugRow struct {
	ID         pgtype.UUID        `json:"id"`
	BrandID    pgtype.UUID        `json:"brand_id"`
	Name       string             `json:"name"`
	Slug       string             `json:"slug"`
	Category   string             `json:"category"`
	Attributes []byte             `json:"attributes"`
	IsLimited  bool               `json:"is_limited"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	BrandName  string             `json:"brand_name"`
	BrandSlug  string             `json:"brand_slug"`
	ImageUrl   string             `json:"image_url"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.Name,
		&i.Slug,
		&i.Category,
		&i.Attributes,
		&i.IsLimited,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BrandName,
		&i.BrandSlug,
		&i.ImageUrl,
	)
	return i, err
}

const listOffersByProductID = `-- name: ListOffersByProductID :many
SELECT po.id, po.product_id, po.store_id, po.price, po.currency, po.in_stock, po.size, po.affiliate_url, po.scraped_at, s.name AS store_name, s.type AS store_type
FROM product_offers po
JOIN stores s ON s.id = po.store_id
WHERE po.product_id = $1
ORDER BY po.price ASC
`

type ListOffersByProductIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	ProductID    pgtype.UUID        `json:"product_id"`
	StoreID      pgtype.UUID        `json:"store_id"`
	Price        pgtype.Numeric     `json:"price"`
	Currency     string             `json:"currency"`
	InStock      bool               `json:"in_stock"`
	Size         pgtype.Text        `json:"size"`
	AffiliateUrl string             `json:"affiliate_url"`
	ScrapedAt    pgtype.Timestamptz `json:"scraped_at"`
	StoreName    string             `json:"store_name"`
	StoreType    string             `json:"store_type"`
}

func (q *Queries) ListOffersByProductID(ctx context.Context, productID pgtype.UUID) ([]ListOffersByProductIDRow, error) {
	rows, err := q.db.Query(ctx, listOffersByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOffersByProductIDRow{}
	for rows.Next() {
		var i ListOffersByProductIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.StoreID,
			&i.Price,
			&i.Currency,
			&i.InStock,
			&i.Size,
			&i.AffiliateUrl,
			&i.ScrapedAt,
			&i.StoreName,
			&i.StoreType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceDropProducts = `-- name: ListPriceDropProducts :many
WITH avg_prices AS (
  SELECT product_id, avg(price)::numeric AS avg_price_30d
  FROM price_history
  WHERE recorded_date >= CURRENT_DATE - interval '30 days'
  GROUP BY product_id
),
current_prices AS (
  SELECT product_id, min(price)::numeric AS current_min_price
  FROM product_offers
  WHERE in_stock = true
  GROUP BY product_id
)
SELECT
  p.id, p.brand_id, p.name, p.slug, p.category, p.attributes, p.is_limited, p.created_at, p.updated_at,
  b.name AS brand_name,
  b.slug AS brand_slug,
  cp.current_min_price AS min_price,
  cp.current_min_price AS max_price,
  COALESCE(AVG(r.rating), 0)::numeric AS avg_rating,
  COALESCE((SELECT url FROM product_images pi WHERE pi.product_id = p.id ORDER BY pi.sort_order LIMIT 1), '')::text AS image_url,
  round((1 - (cp.current_min_price / ap.avg_price_30d)) * 100)::int AS drop_percent
FROM products p
JOIN brands b ON b.id = p.brand_id
JOIN avg_prices ap ON ap.product_id = p.id
JOIN current_prices cp ON cp.product_id = p.id
LEFT JOIN reviews r ON r.product_id = p.id AND r.is_flagged = false
WHERE cp.current_min_price < ap.avg_price_30d * 0.95
GROUP BY p.id, b.name, b.slug, cp.current_min_price, ap.avg_price_30d
ORDER BY drop_percent DESC
LIMIT $1
`

type ListPriceDropProductsRow struct {
	ID          pgtype.UUID        `json:"id"`
	BrandID     pgtype.UUID        `json:"brand_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Category    string             `json:"category"`
	Attributes  []byte             `json:"attributes"`
	IsLimited   bool               `json:"is_limited"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	BrandName   string             `json:"brand_name"`
	BrandSlug   string             `json:"brand_slug"`
	MinPrice    pgtype.Numeric     `json:"min_price"`
	MaxPrice    pgtype.Numeric     `json:"max_price"`
	AvgRating   pgtype.Numeric     `json:"avg_rating"`
	ImageUrl    string             `json:"image_url"`
	DropPercent int32              `json:"drop_percent"`
}

func (q *Queries) ListPriceDropProducts(ctx context.Context, pageLimit int32) ([]ListPriceDropProductsRow, error) {
	rows, err := q.db.Query(ctx, listPriceDropProducts, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPriceDropProductsRow{}
	for rows.Next() {
		var i ListPriceDropProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Name,
			&i.Slug,
			&i.Category,
			&i.Attributes,
			&i.IsLimited,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BrandName,
			&i.BrandSlug,
			&i.MinPrice,
			&i.MaxPrice,
			&i.AvgRating,
			&i.ImageUrl,
			&i.DropPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceHistoryByProductID = `-- name: ListPriceHistoryByProductID :many
SELECT id, product_id, store_id, price, recorded_date
FROM price_history
WHERE product_id = $1
  AND recorded_date >= $2
ORDER BY recorded_date ASC
`

type ListPriceHistoryByProductIDParams struct {
	ProductID    pgtype.UUID `json:"product_id"`
	RecordedDate pgtype.Date `json:"recorded_date"`
}

func (q *Queries) ListPriceHistoryByProductID(ctx context.Context, arg ListPriceHistoryByProductIDParams) ([]PriceHistory, error) {
	rows, err := q.db.Query(ctx, listPriceHistoryByProductID, arg.ProductID, arg.RecordedDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceHistory{}
	for rows.Next() {
		var i PriceHistory
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.StoreID,
			&i.Price,
			&i.RecordedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
  p.id, p.brand_id, p.name, p.slug, p.category, p.attributes, p.is_limited, p.created_at, p.updated_at,
  b.name AS brand_name,
  b.slug AS brand_slug,
  COALESCE(MIN(po.price), 0)::numeric AS min_price,
  COALESCE(MAX(po.price), 0)::numeric AS max_price,
  COALESCE(AVG(r.rating), 0)::numeric AS avg_rating,
  COALESCE((SELECT url FROM product_images pi WHERE pi.product_id = p.id ORDER BY pi.sort_order LIMIT 1), '')::text AS image_url
FROM products p
JOIN brands b ON b.id = p.brand_id
LEFT JOIN product_offers po ON po.product_id = p.id
LEFT JOIN reviews r ON r.product_id = p.id AND r.is_flagged = false
WHERE ($1::uuid IS NULL OR p.brand_id = $1)
  AND ($2::uuid[] IS NULL OR p.brand_id = ANY($2::uuid[]))
  AND ($3::text IS NULL OR p.category = $3)
  AND ($4::boolean IS NULL OR p.is_limited = $4)
  AND ($5::text IS NULL OR p.name ILIKE '%' || $5 || '%')
GROUP BY p.id, b.name, b.slug
ORDER BY p.created_at DESC
LIMIT $7 OFFSET $6
`

type ListProductsParams struct {
	BrandID    pgtype.UUID   `json:"brand_id"`
	BrandIds   []pgtype.UUID `json:"brand_ids"`
	Category   pgtype.Text   `json:"category"`
	IsLimited  pgtype.Bool   `json:"is_limited"`
	Search     pgtype.Text   `json:"search"`
	PageOffset int32         `json:"page_offset"`
	PageLimit  int32         `json:"page_limit"`
}

type ListProductsRow struct {
	ID         pgtype.UUID        `json:"id"`
	BrandID    pgtype.UUID        `json:"brand_id"`
	Name       string             `json:"name"`
	Slug       string             `json:"slug"`
	Category   string             `json:"category"`
	Attributes []byte             `json:"attributes"`
	IsLimited  bool               `json:"is_limited"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	BrandName  string             `json:"brand_name"`
	BrandSlug  string             `json:"brand_slug"`
	MinPrice   pgtype.Numeric     `json:"min_price"`
	MaxPrice   pgtype.Numeric     `json:"max_price"`
	AvgRating  pgtype.Numeric     `json:"avg_rating"`
	ImageUrl   string             `json:"image_url"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.BrandID,
		arg.BrandIds,
		arg.Category,
		arg.IsLimited,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Name,
			&i.Slug,
			&i.Category,
			&i.Attributes,
			&i.IsLimited,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BrandName,
			&i.BrandSlug,
			&i.MinPrice,
			&i.MaxPrice,
			&i.AvgRating,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrendingProducts = `-- name: ListTrendingProducts :many
SELECT
  p.id, p.brand_id, p.name, p.slug, p.category, p.attributes, p.is_limited, p.created_at, p.updated_at,
  b.name AS brand_name,
  b.slug AS brand_slug,
  COALESCE(MIN(po.price), 0)::numeric AS min_price,
  COALESCE(MAX(po.price), 0)::numeric AS max_price,
  COALESCE(AVG(r.rating), 0)::numeric AS avg_rating,
  COALESCE((SELECT url FROM product_images pi WHERE pi.product_id = p.id ORDER BY pi.sort_order LIMIT 1), '')::text AS image_url,
  count(pv.id) AS view_count
FROM products p
JOIN brands b ON b.id = p.brand_id
JOIN product_views pv ON pv.product_id = p.id AND pv.viewed_at >= now() - interval '7 days'
LEFT JOIN product_offers po ON po.product_id = p.id
LEFT JOIN reviews r ON r.product_id = p.id AND r.is_flagged = false
GROUP BY p.id, b.name, b.slug
ORDER BY view_count DESC, p.created_at DESC
LIMIT $1
`

type ListTrendingProductsRow struct {
	ID         pgtype.UUID        `json:"id"`
	BrandID    pgtype.UUID        `json:"brand_id"`
	Name       string             `json:"name"`
	Slug       string             `json:"slug"`
	Category   string             `json:"category"`
	Attributes []byte             `json:"attributes"`
	IsLimited  bool               `json:"is_limited"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	BrandName  string             `json:"brand_name"`
	BrandSlug  string             `json:"brand_slug"`
	MinPrice   pgtype.Numeric     `json:"min_price"`
	MaxPrice   pgtype.Numeric     `json:"max_price"`
	AvgRating  pgtype.Numeric     `json:"avg_rating"`
	ImageUrl   string             `json:"image_url"`
	ViewCount  int64              `json:"view_count"`
}

func (q *Queries) ListTrendingProducts(ctx context.Context, pageLimit int32) ([]ListTrendingProductsRow, error) {
	rows, err := q.db.Query(ctx, listTrendingProducts, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrendingProductsRow{}
	for rows.Next() {
		var i ListTrendingProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.Name,
			&i.Slug,
			&i.Category,
			&i.Attributes,
			&i.IsLimited,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BrandName,
			&i.BrandSlug,
			&i.MinPrice,
			&i.MaxPrice,
			&i.AvgRating,
			&i.ImageUrl,
			&i.ViewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordProductView = `-- name: RecordProductView :exec
INSERT INTO product_views (product_id)
VALUES ($1)
`

func (q *Queries) RecordProductView(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, recordProductView, productID)
	return err
}
