// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddWishlistItem(ctx context.Context, arg AddWishlistItemParams) (Wishlist, error)
	CountUnreadNotifications(ctx context.Context, userID pgtype.UUID) (int64, error)
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreateProductOffer(ctx context.Context, arg CreateProductOfferParams) (ProductOffer, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FlagReviewIfReportsExceedThreshold(ctx context.Context, id pgtype.UUID) error
	GetBrandBySlug(ctx context.Context, slug string) (Brand, error)
	GetEmailVerificationToken(ctx context.Context, tokenHash string) (EmailVerificationToken, error)
	GetLatestExchangeRate(ctx context.Context, arg GetLatestExchangeRateParams) (ExchangeRate, error)
	GetOfferByID(ctx context.Context, id pgtype.UUID) (ProductOffer, error)
	GetOfferByProductAndStore(ctx context.Context, arg GetOfferByProductAndStoreParams) (ProductOffer, error)
	GetPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetSizeConversion(ctx context.Context, arg GetSizeConversionParams) ([]SizeConversionMatrix, error)
	GetStoreByName(ctx context.Context, name string) (Store, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserSizePreferences(ctx context.Context, userID pgtype.UUID) ([]UserSizePreference, error)
	GetWishlistItem(ctx context.Context, id pgtype.UUID) (Wishlist, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	ListBrands(ctx context.Context) ([]Brand, error)
	ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error)
	ListOffersByProductID(ctx context.Context, productID pgtype.UUID) ([]ListOffersByProductIDRow, error)
	ListPriceDropProducts(ctx context.Context, pageLimit int32) ([]ListPriceDropProductsRow, error)
	ListPriceHistoryByProductID(ctx context.Context, arg ListPriceHistoryByProductIDParams) ([]PriceHistory, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	ListReviewsByProduct(ctx context.Context, productID pgtype.UUID) ([]ListReviewsByProductRow, error)
	ListTrendingProducts(ctx context.Context, pageLimit int32) ([]ListTrendingProductsRow, error)
	ListWishlistByUser(ctx context.Context, userID pgtype.UUID) ([]ListWishlistByUserRow, error)
	MarkEmailVerificationTokenUsed(ctx context.Context, id pgtype.UUID) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	MarkPasswordResetTokenUsed(ctx context.Context, id pgtype.UUID) error
	RecordProductView(ctx context.Context, productID pgtype.UUID) error
	RemoveWishlistItem(ctx context.Context, arg RemoveWishlistItemParams) error
	ReplaceProductImage(ctx context.Context, arg ReplaceProductImageParams) error
	ReportReview(ctx context.Context, arg ReportReviewParams) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	SearchBrandsAutocomplete(ctx context.Context, query string) ([]SearchBrandsAutocompleteRow, error)
	SearchProductsAutocomplete(ctx context.Context, query string) ([]SearchProductsAutocompleteRow, error)
	SetUserEmailVerified(ctx context.Context, id pgtype.UUID) error
	SetWishlistAlert(ctx context.Context, arg SetWishlistAlertParams) (Wishlist, error)
	SoftDeleteUser(ctx context.Context, id pgtype.UUID) error
	UpdateProductOffer(ctx context.Context, arg UpdateProductOfferParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertPriceHistoryToday(ctx context.Context, arg UpsertPriceHistoryTodayParams) error
	UpsertProduct(ctx context.Context, arg UpsertProductParams) (Product, error)
	UpsertUserSizePreference(ctx context.Context, arg UpsertUserSizePreferenceParams) (UserSizePreference, error)
}

var _ Querier = (*Queries)(nil)
