// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (product_id, user_id, rating, comment, fit_feedback)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, product_id, user_id, rating, comment, fit_feedback, is_flagged, created_at
`

type CreateReviewParams struct {
	ProductID   pgtype.UUID `json:"product_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Rating      int32       `json:"rating"`
	Comment     pgtype.Text `json:"comment"`
	FitFeedback pgtype.Text `json:"fit_feedback"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.ProductID,
		arg.UserID,
		arg.Rating,
		arg.Comment,
		arg.FitFeedback,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.FitFeedback,
		&i.IsFlagged,
		&i.CreatedAt,
	)
	return i, err
}

const flagReviewIfReportsExceedThreshold = `-- name: FlagReviewIfReportsExceedThreshold :exec
UPDATE reviews r
SET is_flagged = true
WHERE r.id = $1
  AND (SELECT count(*) FROM review_reports rr WHERE rr.review_id = r.id) >= 3
`

func (q *Queries) FlagReviewIfReportsExceedThreshold(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, flagReviewIfReportsExceedThreshold, id)
	return err
}

const listReviewsByProduct = `-- name: ListReviewsByProduct :many
SELECT r.id, r.product_id, r.user_id, r.rating, r.comment, r.fit_feedback, r.is_flagged, r.created_at, u.name AS user_name
FROM reviews r
JOIN users u ON u.id = r.user_id
WHERE r.product_id = $1 AND r.is_flagged = false
ORDER BY r.created_at DESC
`

type ListReviewsByProductRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProductID   pgtype.UUID        `json:"product_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Rating      int32              `json:"rating"`
	Comment     pgtype.Text        `json:"comment"`
	FitFeedback pgtype.Text        `json:"fit_feedback"`
	IsFlagged   bool               `json:"is_flagged"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UserName    string             `json:"user_name"`
}

func (q *Queries) ListReviewsByProduct(ctx context.Context, productID pgtype.UUID) ([]ListReviewsByProductRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsByProductRow{}
	for rows.Next() {
		var i ListReviewsByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
			&i.FitFeedback,
			&i.IsFlagged,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportReview = `-- name: ReportReview :exec
INSERT INTO review_reports (review_id, reported_by, reason)
VALUES ($1, $2, $3)
ON CONFLICT (review_id, reported_by) DO NOTHING
`

type ReportReviewParams struct {
	ReviewID   pgtype.UUID `json:"review_id"`
	ReportedBy pgtype.UUID `json:"reported_by"`
	Reason     pgtype.Text `json:"reason"`
}

func (q *Queries) ReportReview(ctx context.Context, arg ReportReviewParams) error {
	_, err := q.db.Exec(ctx, reportReview, arg.ReviewID, arg.ReportedBy, arg.Reason)
	return err
}
