// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, name, onboarding_focus, preferred_language, preferred_currency, email_verified, deleted_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Name         string `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.OnboardingFocus,
		&i.PreferredLanguage,
		&i.PreferredCurrency,
		&i.EmailVerified,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, onboarding_focus, preferred_language, preferred_currency, email_verified, deleted_at, created_at, updated_at
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.OnboardingFocus,
		&i.PreferredLanguage,
		&i.PreferredCurrency,
		&i.EmailVerified,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, onboarding_focus, preferred_language, preferred_currency, email_verified, deleted_at, created_at, updated_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.OnboardingFocus,
		&i.PreferredLanguage,
		&i.PreferredCurrency,
		&i.EmailVerified,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserEmailVerified = `-- name: SetUserEmailVerified :exec
UPDATE users
SET email_verified = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) SetUserEmailVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setUserEmailVerified, id)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name = $2,
    onboarding_focus = $3,
    preferred_language = $4,
    preferred_currency = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, name, onboarding_focus, preferred_language, preferred_currency, email_verified, deleted_at, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID                pgtype.UUID `json:"id"`
	Name              string      `json:"name"`
	OnboardingFocus   pgtype.Text `json:"onboarding_focus"`
	PreferredLanguage string      `json:"preferred_language"`
	PreferredCurrency string      `json:"preferred_currency"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.Name,
		arg.OnboardingFocus,
		arg.PreferredLanguage,
		arg.PreferredCurrency,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.OnboardingFocus,
		&i.PreferredLanguage,
		&i.PreferredCurrency,
		&i.EmailVerified,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
