// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wishlists.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWishlistItem = `-- name: AddWishlistItem :one
INSERT INTO wishlists (user_id, product_id, alert_active, alert_type)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, product_id) DO UPDATE SET alert_active = EXCLUDED.alert_active
RETURNING id, user_id, product_id, alert_active, alert_type, created_at
`

type AddWishlistItemParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ProductID   pgtype.UUID `json:"product_id"`
	AlertActive bool        `json:"alert_active"`
	AlertType   pgtype.Text `json:"alert_type"`
}

func (q *Queries) AddWishlistItem(ctx context.Context, arg AddWishlistItemParams) (Wishlist, error) {
	row := q.db.QueryRow(ctx, addWishlistItem,
		arg.UserID,
		arg.ProductID,
		arg.AlertActive,
		arg.AlertType,
	)
	var i Wishlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.AlertActive,
		&i.AlertType,
		&i.CreatedAt,
	)
	return i, err
}

const getWishlistItem = `-- name: GetWishlistItem :one
SELECT id, user_id, product_id, alert_active, alert_type, created_at
FROM wishlists
WHERE id = $1
`

func (q *Queries) GetWishlistItem(ctx context.Context, id pgtype.UUID) (Wishlist, error) {
	row := q.db.QueryRow(ctx, getWishlistItem, id)
	var i Wishlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.AlertActive,
		&i.AlertType,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveAlertSubscribersForProduct = `-- name: ListActiveAlertSubscribersForProduct :many
SELECT w.id AS wishlist_id, w.alert_type, u.id AS user_id, u.email, u.name
FROM wishlists w
JOIN users u ON u.id = w.user_id
WHERE w.product_id = $1 AND w.alert_active = true AND u.deleted_at IS NULL
`

type ListActiveAlertSubscribersForProductRow struct {
	WishlistID pgtype.UUID `json:"wishlist_id"`
	AlertType  pgtype.Text `json:"alert_type"`
	UserID     pgtype.UUID `json:"user_id"`
	Email      string      `json:"email"`
	Name       string      `json:"name"`
}

func (q *Queries) ListActiveAlertSubscribersForProduct(ctx context.Context, productID pgtype.UUID) ([]ListActiveAlertSubscribersForProductRow, error) {
	rows, err := q.db.Query(ctx, listActiveAlertSubscribersForProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAlertSubscribersForProductRow{}
	for rows.Next() {
		var i ListActiveAlertSubscribersForProductRow
		if err := rows.Scan(
			&i.WishlistID,
			&i.AlertType,
			&i.UserID,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWishlistByUser = `-- name: ListWishlistByUser :many
SELECT w.id, w.user_id, w.product_id, w.alert_active, w.alert_type, w.created_at, p.name AS product_name, p.slug AS product_slug, p.brand_id
FROM wishlists w
JOIN products p ON p.id = w.product_id
WHERE w.user_id = $1
ORDER BY w.created_at DESC
`

type ListWishlistByUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ProductID   pgtype.UUID        `json:"product_id"`
	AlertActive bool               `json:"alert_active"`
	AlertType   pgtype.Text        `json:"alert_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProductName string             `json:"product_name"`
	ProductSlug string             `json:"product_slug"`
	BrandID     pgtype.UUID        `json:"brand_id"`
}

func (q *Queries) ListWishlistByUser(ctx context.Context, userID pgtype.UUID) ([]ListWishlistByUserRow, error) {
	rows, err := q.db.Query(ctx, listWishlistByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWishlistByUserRow{}
	for rows.Next() {
		var i ListWishlistByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.AlertActive,
			&i.AlertType,
			&i.CreatedAt,
			&i.ProductName,
			&i.ProductSlug,
			&i.BrandID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWishlistItem = `-- name: RemoveWishlistItem :exec
DELETE FROM wishlists
WHERE id = $1 AND user_id = $2
`

type RemoveWishlistItemParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveWishlistItem(ctx context.Context, arg RemoveWishlistItemParams) error {
	_, err := q.db.Exec(ctx, removeWishlistItem, arg.ID, arg.UserID)
	return err
}

const setWishlistAlert = `-- name: SetWishlistAlert :one
UPDATE wishlists
SET alert_active = $3, alert_type = $4
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, product_id, alert_active, alert_type, created_at
`

type SetWishlistAlertParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	AlertActive bool        `json:"alert_active"`
	AlertType   pgtype.Text `json:"alert_type"`
}

func (q *Queries) SetWishlistAlert(ctx context.Context, arg SetWishlistAlertParams) (Wishlist, error) {
	row := q.db.QueryRow(ctx, setWishlistAlert,
		arg.ID,
		arg.UserID,
		arg.AlertActive,
		arg.AlertType,
	)
	var i Wishlist
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.AlertActive,
		&i.AlertType,
		&i.CreatedAt,
	)
	return i, err
}
